from enum import Enum

# These effects have been programmed on the Pico.
class Effect(Enum):
    # LED Strip Effects (Pico)
    STATIC = "STATIC"
    RAINBOW = "RAINBOW"
    RAINBOW_CYCLE = "RAINBOW_CYCLE"
    THEATER_CHASE = "THEATER_CHASE"
    THEATER_CHASE_RAINBOW = "THEATER_CHASE_RAINBOW"
    COLOR_WIPE = "COLOR_WIPE"
    SCANNER = "SCANNER"
    FADE = "FADE"
    SPARKLE = "SPARKLE"
    FLASH = "FLASH"
    PULSATE = "PULSATE"
    CHASE = "CHASE"
    CLEAR = "CLEAR"
    BPMFLASH = "BPMFLASH"
    FADEIN = "FADEIN"
    FADEOUT = "FADEOUT"
    DIM = "DIM"
    
    # DMX Effects (Pi 1B)
    DMX_DIMMER = "DMX_DIMMER"
    DMX_STROBE = "DMX_STROBE"
    DMX_BLACKOUT = "DMX_BLACKOUT"
    DMX_COLOR = "DMX_COLOR"
    DMX_FADE_UP = "DMX_FADE_UP"
    DMX_FADE_DOWN = "DMX_FADE_DOWN"
    DMX_FLASH = "DMX_FLASH"
    DMX_PULSE = "DMX_PULSE"
    DMX_CHASE = "DMX_CHASE"
    